### ISSUE TITLE
duckduckgo_search这个用不了，能换其他的么

### ISSUE THREAD

**Issue by EvilCalf** [yanqiangmiffy/Chinese-LangChain#14]
web搜索功能，谢谢

**Comment by jiangliqin** [comment]
我也用不了，请问有平替方案吗？

**Comment by wusongbai139** [comment]
我也遇到报错了：
(env) PS H:\agent\Chinese-LangChain>     python main.py
2024-01-18 13:39:27,323 [INFO] [_client.py:1027] HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "H:\agent\Chinese-LangChain\main.py", line 6, in <module>
    from clc.langchain_application import LangChainApplication
  File "H:\agent\Chinese-LangChain\clc\langchain_application.py", line 17, in <module>
    from clc.source_service import SourceService
  File "H:\agent\Chinese-LangChain\clc\source_service.py", line 15, in <module>
    from duckduckgo_search import ddg
ImportError: cannot import name 'ddg' from 'duckduckgo_search' (H:\agent\Chinese-LangChain\env\lib\site-packages\duckduckgo_search\__init__.py)

**Comment by wusongbai139** [comment]
已经解决，安装duckduckgo_search的2023年的4月份的版本就行
