### ISSUE TITLE
ModuleNotFoundError: No module named 'mdtex2html'

### ISSUE THREAD

**Issue by minlo-18** [yanqiangmiffy/Chinese-LangChain#23]
C:\Users\admin\Desktop\Chinese-LangChain-master>py main.py
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Chinese-LangChain-master\main.py", line 4, in <module>
    from app_modules.overwrites import postprocess
  File "C:\Users\admin\Desktop\Chinese-LangChain-master\app_modules\overwrites.py", line 5, in <module>
    from app_modules.utils import *
  File "C:\Users\admin\Desktop\Chinese-LangChain-master\app_modules\utils.py", line 8, in <module>
    import mdtex2html
ModuleNotFoundError: No module named 'mdtex2html'

**Comment by minlo-18** [comment]
安装了mdtex2html也不行，是不是版本不对？ 你们这requirements给的不全啊。。

**Comment by minlo-18** [comment]
能不能整个一键包整合包之类的。。。 这些依赖a依赖b的倒腾不清啊。。。QAQ
