### ISSUE TITLE
python main.py报错，请问如何解决

### ISSUE THREAD

**Issue by ivrrtts629** [yanqiangmiffy/Chinese-LangChain#40]
Traceback (most recent call last):
  File "/root/Chinese-LangChain/main.py", line 26, in <module>
    application = LangChainApplication(config)
  File "/root/Chinese-LangChain/clc/langchain_application.py", line 24, in __init__
    self.llm_service.load_model(model_name_or_path=self.config.llm_model_name)
  File "/root/Chinese-LangChain/clc/gpt_service.py", line 55, in load_model
    self.tokenizer = AutoTokenizer.from_pretrained(
  File "/root/anaconda3/envs/langchain/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 721, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.THUDM.chatglm-6b-int4-qe.977d9df4cfae6b7a756e07698483872c5c070eee.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

**Comment by dage0127** [comment]
是不是网络不好。
可以手动下载模型文件，设置模型地址。再试一下。
国内下载地址会快一些：https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/

**Comment by dkw-wkd** [comment]
> 是不是网络不好。 可以手动下载模型文件，设置模型地址。再试一下。 国内下载地址会快一些：https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/

兄弟 想请教下设置模型地址，具体要修改哪些路径呢？

**Comment by ocpinfo** [comment]
我运行main.py的时候出现下面这个错误，请问怎么解决呢？
2023-09-09 18:14:12,069 [INFO] [loader.py:64] Loading faiss.
2023-09-09 18:14:12,225 [INFO] [loader.py:66] Successfully loaded faiss.
Traceback (most recent call last):
  File "/Users/wpeng/Desktop/ChatGLM2-6B/Chinese-LangChain/main.py", line 153, in <module>
    kg_name = gr.Radio(list(config.kg_vector_stores.keys()),
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by ocpinfo** [comment]
已解决，kg不能设置成None
