### ISSUE TITLE
运行main.py时遇到报错cannot import name 'ddg' from 'duckduckgo_search' 

### ISSUE THREAD

**Issue by wusongbai139** [yanqiangmiffy/Chinese-LangChain#53]
报错内容：
(env) PS H:\agent\Chinese-LangChain>     python main.py
2024-01-18 13:39:27,323 [INFO] [_client.py:1027] HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "H:\agent\Chinese-LangChain\main.py", line 6, in <module>
    from clc.langchain_application import LangChainApplication
  File "H:\agent\Chinese-LangChain\clc\langchain_application.py", line 17, in <module>
    from clc.source_service import SourceService
  File "H:\agent\Chinese-LangChain\clc\source_service.py", line 15, in <module>
    from duckduckgo_search import ddg
ImportError: cannot import name 'ddg' from 'duckduckgo_search' (H:\agent\Chinese-LangChain\env\lib\site-packages\duckduckgo_search\__init__.py)

我有“duckduckgo_search”，但是其文件下没有ddg文件，我想知道如何解决，或者duckduckgo在整个项目中有没有别的替代方案

**Comment by wusongbai139** [comment]
已经解决，安装duckduckgo_search的2023年的4月份的版本就行

**Comment by dingzt97** [comment]
您好，方便告知一下duckduckgo_search的版本号吗

**Comment by Qlalq** [comment]
pip install duckduckgo-search==2.9.0
